import './globals.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import {config} from 'dotenv';
config();

const raleway = Raleway({ subsets: ['latin'], weight: ['400', '700'], })

export const metadata: Metadata = {
  title: 'NextJS Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>{children}</body>
    </html>
  )
}
